<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="CS.Default" %>

<!DOCTYPE html>

<script runat="server">
    /*
    protected void Page_Load(object sender, EventArgs e)
    {
        myTimeLabel2.Text = DateTime.Now.ToString();
    }
    */

</script>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Welcome to Build Your Own ASP.NET 3.5 Web Site!</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <p>Hello there!</p>
        <p>
            The time is now: <asp:Label ID="myTimeLabel" runat="server" />
        </p>
        <p>
            The time is now: <asp:Label ID="myTimeLabel2" runat="server" />
        </p>
        <p>
            <%-- Declare the title as string and set it --%>
            <% string Title = "This is generated by a code render block."; %>
            <%=Title %>
        </p>
    </div>
    </form>
</body>
</html>
